---
- block:
   - name: File Audit Logging Status
     shell:
      cmd: "/usr/lpp/mmfs/bin/mmaudit all list -Y"
     register: auditlogin_status
     ignore_errors: true

   - name: File Audit Logging Running Status
     debug:
       msg: "{{ auditlogin_status.stdout }}"

  run_once: true
